version: '3.1'

services:

  mongo:
    image: mongo
    volumes:
    - "/tmp/db:/data/db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456

  ssq:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
